services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: ergoai_db_simple
    environment:
      POSTGRES_DB: ergoai_db
      POSTGRES_USER: ergoai_user
      POSTGRES_PASSWORD: simple_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Backend API - now with real ErgoAI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: ergoai_backend_simple
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://ergoai_user:simple_password@postgres:5432/ergoai_db
      - SECRET_KEY=simple-dev-key
      - ERGOAI_PATH=/opt/ergoai
    volumes:
      - ./ergoai:/opt/ergoai:ro  # Mount your ErgoAI installation
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  # Web Interface
  frontend:
    image: nginx:alpine
    container_name: ergoai_web_simple
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
  ergoai_data:
