(TeX-add-style-hook "sgml2pl"
 (lambda ()
    (LaTeX-add-index-entries
     "\\texttt{CDATA}"
     "\\texttt{load\\_sgml\\_structure/3}"
     "\\texttt{load\\_xml\\_structure/3}"
     "\\texttt{load\\_html\\_structure/3}"
     "\\texttt{load\\_xhtml\\_structure/3}"
     "\\texttt{load\\_structure/4}"
     "\\texttt{NAMES}"
     "\\texttt{NUMBER}"
     "\\texttt{SDATA}"
     "\\texttt{NDATA}"
     "\\texttt{xml}"
     "\\texttt{sgml}"
     "\\texttt{xmlns}"
     "\\texttt{token}"
     "\\texttt{integer}"
     "\\texttt{false}"
     "\\texttt{sgml} space mode"
     "\\texttt{default} space mode"
     "\\texttt{preserve} space mode"
     "\\texttt{remove} space mode"
     "\\texttt{xmlns} dialect"
     "\\texttt{new\\_dtd/2}"
     "\\texttt{free\\_dtd/1}"
     "\\texttt{open\\_dtd/3}"
     "\\texttt{dtd/3}"
     "\\texttt{doctype}"
     "\\texttt{new\\_sgml\\_parser/2}"
     "\\texttt{free\\_sgml\\_parser/1}"
     "\\texttt{set\\_sgml\\_parser/2}"
     "\\texttt{sgml\\_parse/3}"
     "\\texttt{file}"
     "\\texttt{element}"
     "\\texttt{declaration}"
     "\\texttt{informational}"
     "\\texttt{DOCTYPE} declaration"
     "\\texttt{parse\\_xpath/4}")
    (LaTeX-add-labels
     "sec:space"
     "sec:xml"
     "sec:xmlns"
     "sec-xpath")))

