version: "3.3"
services:
    trankit:
        build:
            context: .
        container_name: 'fnbr-ergoai-$PROJECT_NAME'
        environment:
            - ERGOROOT=/ergo/Coherent/ERGOAI_3.0/ErgoAI
            - XSBARCHDIR=/ergo/Coherent/ERGOAI_3.0/XSB/config/x86_64-pc-linux-gnu
        restart: unless-stopped
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ${DOCUMENT_ROOT}:/app
            - ${DOCUMENT_ROOT}/ergo:/ergo
