(TeX-add-style-hook "system"
 (lambda ()
    (LaTeX-add-index-entries
     "base file name"
     "source file designator"
     "load search path"
     "environment variables!{\\tt XSB\\_USER\\_AUXDIR}"
     ".xsb/ configuration directory"
     "xsbrc.P initialization file"
     "packages"
     "packages!\\texttt{unload\\_package/1}"
     "packages!\\texttt{package\\_configuration/2}"
     "emulator!command line options"
     "options!command line arguments"
     "stacks!default sizes"
     "stacks!expanding"
     "tabling!call subsumption"
     "scripting"
     "shared\\_predicates"
     "garbage collection"
     "memory management"
     "garbage collection!dynamic clauses"
     "garbage collection!tables"
     "Prolog flags!{\\tt max\\_memory}"
     "dynamic code!loading"
     "canonical format"
     "dynamic code!advantages and disadvantages"
     "declarations!\\texttt{multifile/2}"
     "compiler"
     "byte code!files!compiler"
     "compiler!\\texttt{cmplib}"
     "GPP"
     "preprocessing"
     "invoking the Compiler"
     "compiler!invoking"
     "compiler!options"
     "options!compiler"
     "compiler options!\\texttt{optimize}"
     "compiler options!\\texttt{dynamic/1}"
     "Unicode!character\\_sets"
     "compiler options!\\texttt{character\\_set/1}"
     "modules!explicit filenames"
     "compiler options!\\texttt{module/1}"
     "standard predicates"
     "compiler
  options!\\texttt{xpp\\_on}"
     "GPP!\\texttt{gpp\\_include\\_dir}"
     "compilation!conditional!gpp"
     "GPP!\\texttt{gpp\\_options}"
     "GPP!\\texttt{xpp\\_dump}"
     "GPP!\\texttt{xpp\\_on/N}"
     "GPP!\\texttt{xpp\\_dump/N}"
     "GPP!\\texttt{quit\\_on\\_error}"
     "tabling!compiler options"
     "tabling!automatic"
     "declarations!\\texttt{auto\\_table}"
     "tabling!supplemental"
     "declarations!\\texttt{suppl\\_table}"
     "specialization!compiler options"
     "compiler options!\\texttt{spec\\_repr}"
     "compiler options!\\texttt{spec\\_off}"
     "compiler options!\\texttt{unfold\\_off}"
     "compiler options!\\texttt{spec\\_dump}"
     "compiler options!\\texttt{init\\_var\\_off}"
     "mode analysis!compiler options"
     "static analysis!mode"
     "modes!annotations"
     "compiler options!\\texttt{modeinfer}"
     "compiler options!\\texttt{mi\\_warn}"
     "compiler!specialization"
     "specialization!Compiler"
     "compiler!directives"
     "directives!Compiler"
     "compilation!conditional!Prolog directives"
     "mode analysis!mode indicators"
     "modes!directives"
     "directives!modes"
     "modes!indicators"
     "tabling!directives"
     "directives!tabling"
     "static analysis!auto\\_table"
     "static analysis!suppl\\_table"
     "termination"
     "indexing!directives"
     "directives!indexing"
     "dynamic code!indexing"
     "Unicode"
     "compiler!inlines"
     "inlines!compiler"
     "ISO Compatibility")
    (LaTeX-add-labels
     "chap:system"
     "sec:filenames"
     "sec:standard"
     "LibPath"
     "sec:search-path"
     "sec-user-config-dir"
     "sec:EmuOptions"
     "sec:memory-flags"
     "memory_management"
     "Consulting"
     "sec:dynamic-code"
     "the_compiler"
     "compiler_invoking"
     "sec:CompilerOptions"
     "specialization"
     "compiler_directives"
     "mode_declarations"
     "tabling_directives"
     "indexing_directives"
     "other-directives"
     "inline_predicates"
     "inlinepredicatetable"
     "sec:iso")
    (TeX-run-style-hooks
     "module_system")))

