services:
  # Working Backend (no database dependency)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.working
    container_name: ergoai_backend_working
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - ergoai_network

  # ErgoAI Service (your working container)
  ergoai:
    build:
      context: ./ergoai-service
      dockerfile: Dockerfile
    container_name: ergoai_service
    environment:
      - ERGOROOT=/ergo/Coherent/ERGOAI_3.0/ErgoAI
      - XSBARCHDIR=/ergo/Coherent/ERGOAI_3.0/XSB/config/x86_64-pc-linux-gnu
    volumes:
      - ergoai_data:/ergo
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - ergoai_network

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: ergoai_nginx_working
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ergoai_network

volumes:
  ergoai_data:

networks:
  ergoai_network:
    driver: bridge
