# docker-compose.simple.yml
# SIMPLE ErgoAI Web Interface - Just the basics!

services:
  # Database to save your knowledge bases
  postgres:
    image: postgres:15
    container_name: ergoai_db
    environment:
      POSTGRES_DB: ergoai_db
      POSTGRES_USER: ergoai_user
      POSTGRES_PASSWORD: simple_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend API - connects to ErgoAI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: ergoai_backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://ergoai_user:simple_password@postgres:5432/ergoai_db
      - SECRET_KEY=simple-dev-key
      - ERGOAI_PATH=/opt/ergoai
    volumes:
      - ./backend:/app
      - ergoai_data:/opt/ergoai
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  # Web Interface (using the HTML we created)
  frontend:
    image: nginx:alpine
    container_name: ergoai_web
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
  ergoai_data:
